---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:../sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
---
spring:
  profiles: container
  datasource:
    url: "jdbc:sqlite:/var/jumajumo/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
